spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
        resources:
            mapping: /skin/**
            location: /skin/

    jpa:
        hibernate:
            ddl-auto: create
            dialect: org.hibernate.dialect.MySQL5Dialect
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        generate-ddl: false
        database: mysql
        show-sql: true
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                format_sql: true
                c3p0:
                  minPoolSize: 50
    datasource:
        tomcat:
          max-wait: 10000
          max-active: 50
          initial-size: 20
        url: jdbc:log4jdbc:mysql://localhost:3306/ucbb_2?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC
        username: maum
        password: ggoggoma
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        type: org.apache.tomcat.jdbc.pool.DataSource



